import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-transparent`}
    >
      <body className="h-full bg-transparent overflow-hidden p-0 m-0">
        <main className="h-full w-full overflow-hidden bg-[var(--background)] text-[var(--foreground)] flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
